name: 💡 Feature
description: Have a new idea/feature? Please suggest 😄!
title: "[FEATURE] <description>"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the feature you wish to have in the Project 
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?(any dependency changes/ Miscellaneous Info)
    validations:
      required: false